//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visualizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visualizer.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory: .
        /// </summary>
        public static string AdvisoryProgressBar {
            get {
                return ResourceManager.GetString("AdvisoryProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team allocation:.
        /// </summary>
        public static string AllocationLabel {
            get {
                return ResourceManager.GetString("AllocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack: .
        /// </summary>
        public static string AttackProgressBar {
            get {
                return ResourceManager.GetString("AttackProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker error.
        /// </summary>
        public static string Checker_Error {
            get {
                return ResourceManager.GetString("Checker_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By circle.
        /// </summary>
        public static string CircleAllocation {
            get {
                return ResourceManager.GetString("CircleAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsed teams.
        /// </summary>
        public static string CollapsedTeamsButton {
            get {
                return ResourceManager.GetString("CollapsedTeamsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defence: .
        /// </summary>
        public static string DefenceProgressBar {
            get {
                return ResourceManager.GetString("DefenceProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string FiltersButton {
            get {
                return ResourceManager.GetString("FiltersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By grid.
        /// </summary>
        public static string GridAllocation {
            get {
                return ResourceManager.GetString("GridAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time.
        /// </summary>
        public static string RealtimeCheckbox {
            get {
                return ResourceManager.GetString("RealtimeCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By rectangle.
        /// </summary>
        public static string RectangleAllocation {
            get {
                return ResourceManager.GetString("RectangleAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Service_DOWN {
            get {
                return ResourceManager.GetString("Service_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mumble.
        /// </summary>
        public static string Service_MUMBLE {
            get {
                return ResourceManager.GetString("Service_MUMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven&apos;t a flag.
        /// </summary>
        public static string Service_NOTFLAG {
            get {
                return ResourceManager.GetString("Service_NOTFLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Service_OK {
            get {
                return ResourceManager.GetString("Service_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Service_UNKNOWN {
            get {
                return ResourceManager.GetString("Service_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service status:.
        /// </summary>
        public static string ServiceStatus {
            get {
                return ResourceManager.GetString("ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show attacks in the past.
        /// </summary>
        public static string ShowAttacksCheckbox {
            get {
                return ResourceManager.GetString("ShowAttacksCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showed teams.
        /// </summary>
        public static string ShowedTeamsButton {
            get {
                return ResourceManager.GetString("ShowedTeamsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show states of services preview.
        /// </summary>
        public static string ShowPreviewCheckbox {
            get {
                return ResourceManager.GetString("ShowPreviewCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks: .
        /// </summary>
        public static string TasksProgressBar {
            get {
                return ResourceManager.GetString("TasksProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams filter.
        /// </summary>
        public static string TeamsFilterWindow {
            get {
                return ResourceManager.GetString("TeamsFilterWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: .
        /// </summary>
        public static string TotalProgressBar {
            get {
                return ResourceManager.GetString("TotalProgressBar", resourceCulture);
            }
        }
    }
}
