CREATE ROLE ructfe NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
ALTER USER ructfe WITH PASSWORD 'U6ww3QZwZ09yIFLOwmEJd7LDKwC8oZeX';

CREATE DATABASE ructfe11 OWNER ructfe;
CREATE DATABASE ructfe12 OWNER ructfe;
CREATE DATABASE ructfe13 OWNER ructfe;

CREATE DATABASE ructfe21 OWNER ructfe;
CREATE DATABASE ructfe22 OWNER ructfe;

