help:
	echo Targets: main-db test-db test-tiny-db

main-db:
	./run.sh drop.sql
	./run.sh create.sql
	./run.sh data.ructfe.sql
#	./run.sh teams.sql
#	./run.sh advauths.sql

test-db:
	./run.sh drop.sql
	./run.sh create.sql
	./run.sh data.test.sql
